name: "Auto Changelog"

on:
  release:
    types: [push, released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Changelog
      uses: ardalanamini/auto-changelog@v3
      id: changelog
